---
- name: Deploiement de l'appli fake-backend comme  frontend battleboat
  hosts: web 
  gather_facts: yes
  become: true


  vars_files:
    - "vars/secret.yml"
    - "vars/main.yml"

  vars:
    pip_install_packages:
      - name: docker

  pre_tasks:
  - name: update all packages 
    yum:
      name: '*'
      update_only: yes
      update_cache: yes
      state: latest 

  - name: Install epel release
    yum: 
      name: epel-release
      state: installed

  roles:
    - role: 'geerlingguy.pip'
    - role: 'geerlingguy.docker'
    - role: 'geerlingguy.git' 
    - role: 'roles/backend'
    - role: 'roles/frondend'
  
