---
- name: Deploiement de l'appli fake-backend comme  frontend battleboat
  hosts: web 
  gather_facts: yes
  become: true


  vars_files:
    - "vars/secret.yml"
    - "vars/main.yml"

  vars:
    pip_install_packages:
      - name: docker

  pre_tasks:
  - name: upgrade all packages 
    yum:
      name: '*'
      state: latest 

  - name: Install epel release
    yum: 
      name: epel-release
      state: installed

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
 
  tasks:
   
  - name: Create a volume
    docker_volume:
      name: mysql_data

  - name: Create a global network of our two containers
    docker_network:
      name: network_game
 
#  Deploiement du container dbgame du BACKEND
  - name: Deploiement de la base de données (Mysql:5.7) BACKEND
    docker_container:
      name: dbgame
      image: mysql:5.7
      state: started
      env:
        MYSQL_ROOT_PASSWORD: rootpwdgame
        MYSQL_DATABASE: battleboat
        MYSQL_USER: battleuser
        MYSQL_PASSWORD: battlepass

      volumes:
        - mysql_data:/var/lib/mysql
      networks:
      - name: network_game 


# Deploiement de l'appli web battleboat (battlegame) FRONDEND


  - name: Log into DockerHub
    docker_login:
      username: "{{ dockerhub_login_vault }}"
      password: "{{ dockerhub_pwd_vault }}"
   
  - name: pull an image
    docker_image:
      name: "{{ dockerhub_login_vault }}/fake_backend:latest" 
      source: pull

  - name: container battlegame
    docker_container:
      name: battlegame
      image: "{{ dockerhub_login_vault }}/fake_backend:latest"
      state: started
   
      ports:
        - "5252:3000"
      env:
        DATABASE_HOST: "dbgame"
        DATABASE_PORT: "3306"
        DATABASE_USER: "battleuser"
        DATABASE_PASSWORD: "battlepass"
        DATABASE_NAME: "battleboat"

      volumes:
        - "battleboat:/etc/backend/static"
      networks:
        - name: network_game    
