---

# Deploiement de l'appli web battleboat (battlegame) FRONDEND

- name: create project directory
  file:
    path: "{{home}}/mini_projet"
    state: directory

- name: copy devops private key file
  copy:
    content: "{{ github_private_key }}"
    dest: "{{home}}/.ssh/id_rsa"
    owner: centos

- name: load the source code in github
  git:
    repo: "{{ repo_fake_backend  }}"
    dest: "{{home}}/mini_projet"
    accept_hostkey: yes
    force: yes
    recursive: no
    key_file: "{{ home }}/.ssh/id_rsa"
    version: "{{ tag_version }}"

- name: Log into DockerHub
  docker_login:
    username: "{{ dockerhub_login_vault }}"
    password: "{{ dockerhub_pwd_vault }}"

- name: pull an image
  docker_image:
    name: "{{ dockerhub_login_vault }}/fake_backend:latest"
    source: pull

- name: container battlegame
  docker_container:
    name: battlegame
    image: "{{ dockerhub_login_vault }}/fake_backend:latest"
    state: started

    ports:
      - "5050:3000"
    env:
      DATABASE_HOST: "dbgame"
      DATABASE_PORT: "3306"
      DATABASE_USER: "battleuser"
      DATABASE_PASSWORD: "battlepass"
      DATABASE_NAME: "battleboat"

      volumes:
        - "{{home}}/mini_projet/battleboat:/etc/backend/static"
      networks:
        - name: network_game

